"""
sda index — generate or validate the knowledge graph index.

Usage:
  sda index             # generate architecture/index.yaml
  sda index --validate  # check if committed index is up to date (non-blocking)
"""

import re
import yaml
from pathlib import Path
from typing import Annotated

import typer
from rich import print as rprint
from rich.table import Table

INBOX_DIR = Path("architecture/inbox")
ADR_DIR = Path("architecture/adr")
INDEX_FILE = Path("architecture/index.yaml")
TEMPLATE_FILE = "TEMPLATE.md"

_META_RE = re.compile(r"##\s+Metadata\s*\n((?:\s*-\s+[\w_]+:.*\n?)*)", re.MULTILINE)
_FIELD_RE = re.compile(r"-\s+([\w_]+):\s*(.*)")
_SERVICES_RE = re.compile(r"##\s+Affected Services\s*\n((?:\s*-\s+.*\n?)*)", re.MULTILINE)


def _parse_meta_fields(content: str) -> dict:
    match = _META_RE.search(content)
    if not match:
        return {}
    fields: dict = {}
    for line in match.group(1).splitlines():
        m = _FIELD_RE.match(line.strip())
        if m:
            k, v = m.group(1), m.group(2).strip()
            if v in ("~", "", "null"):
                fields[k] = None
            elif v.startswith("[") and v.endswith("]"):
                inner = v[1:-1].strip()
                fields[k] = [x.strip() for x in inner.split(",") if x.strip()] if inner else []
            else:
                fields[k] = v
    return fields


def _affected_services(content: str) -> list[str]:
    m = _SERVICES_RE.search(content)
    if not m:
        return []
    return [l.strip().lstrip("- ").strip() for l in m.group(1).splitlines() if l.strip().lstrip("- ").strip()]


def _build_graph(project_dir: Path) -> dict:
    from collections import defaultdict

    inbox = project_dir / INBOX_DIR
    adr_dir = project_dir / ADR_DIR
    graph: dict = {}
    service_index: dict = defaultdict(lambda: {"problems": [], "adrs": []})

    # Problems
    if inbox.exists():
        for f in sorted(inbox.glob("PROB-[0-9]*.yaml")):
            with f.open(encoding="utf-8") as fh:
                data = yaml.safe_load(fh) or {}
            prob_id = data.get("id") or f.stem.upper()
            services = data.get("services") or []
            graph[prob_id] = {
                "type": "problem",
                "services": services,
                "status": data.get("status", "active"),
                "linked_adrs": [],
            }
            for svc in services:
                if prob_id not in service_index[svc]["problems"]:
                    service_index[svc]["problems"].append(prob_id)

    # ADRs
    if adr_dir.exists():
        for f in sorted(adr_dir.glob("*.md")):
            if f.name == TEMPLATE_FILE:
                continue
            content = f.read_text(encoding="utf-8")
            meta = _parse_meta_fields(content)
            if not meta:
                continue
            adr_id = f.stem.upper()
            links = meta.get("links") or []
            if isinstance(links, str):
                links = [links]
            prob_links = [l for l in links if l.startswith("PROB-")]
            adr_services = _affected_services(content)
            graph[adr_id] = {
                "type": "adr",
                "status": meta.get("status", "proposed"),
                "linked_problems": prob_links,
                "linked_services": adr_services,
                "superseded_by": meta.get("superseded_by"),
            }
            for prob_id in prob_links:
                if prob_id in graph and adr_id not in graph[prob_id]["linked_adrs"]:
                    graph[prob_id]["linked_adrs"].append(adr_id)
            for svc in adr_services:
                if adr_id not in service_index[svc]["adrs"]:
                    service_index[svc]["adrs"].append(adr_id)

    # Service nodes
    for svc_name, svc_data in service_index.items():
        graph[svc_name] = {
            "type": "service",
            "problems": svc_data["problems"],
            "adrs": svc_data["adrs"],
        }

    return graph


def _render(graph: dict) -> str:
    header = "# AUTO-GENERATED by `sda index` — do not edit manually\n"
    return header + yaml.dump({"graph": graph}, default_flow_style=False, sort_keys=True, allow_unicode=True)


def index(
    validate: Annotated[bool, typer.Option("--validate", help="Validate committed index is up to date (non-blocking)")] = False,
    project_dir: Annotated[Path, typer.Option(help="Project root directory")] = Path("."),
) -> None:
    """Generate or validate the architecture/index.yaml knowledge graph."""
    graph = _build_graph(project_dir)
    output = _render(graph)
    index_file = project_dir / INDEX_FILE

    n_problems = sum(1 for v in graph.values() if v.get("type") == "problem")
    n_adrs = sum(1 for v in graph.values() if v.get("type") == "adr")
    n_services = sum(1 for v in graph.values() if v.get("type") == "service")

    if validate:
        if not index_file.exists():
            rprint("[yellow]WARNING:[/yellow] architecture/index.yaml not found — run [bold]sda index[/bold] to generate")
            raise typer.Exit(0)
        committed = index_file.read_text(encoding="utf-8")
        if committed != output:
            rprint("[yellow]WARNING:[/yellow] architecture/index.yaml is stale — run [bold]sda index[/bold] to regenerate")
        else:
            rprint("[green]✓[/green] knowledge graph index is up to date")
        raise typer.Exit(0)

    index_file.parent.mkdir(parents=True, exist_ok=True)
    index_file.write_text(output, encoding="utf-8")

    table = Table(title="Knowledge Graph", show_header=True, header_style="bold cyan")
    table.add_column("Type")
    table.add_column("Count", justify="right")
    table.add_row("Problems", str(n_problems))
    table.add_row("ADRs", str(n_adrs))
    table.add_row("Services", str(n_services))

    from rich.console import Console
    Console().print(table)
    rprint(f"\n[green]✓[/green] Written to {index_file}")
