"""
sda init — scaffold a new SDA project from bundled templates.

Usage:
  sda init           # scaffold in current directory
  sda init ./my-project
"""

import shutil
from pathlib import Path
from importlib import resources
from typing import Annotated

import typer
from rich import print as rprint
from rich.panel import Panel

SCAFFOLD_DIRS = [
    "architecture/inbox",
    "architecture/adr",
    "architecture/model",
    "schemas",
    ".github/workflows",
]

CREATED: list[str] = []


def _templates_dir() -> Path:
    """Locate bundled templates — works both installed and from source."""
    try:
        ref = resources.files("aos") / "templates"
        # Materialise to a real path
        with resources.as_file(ref) as p:
            if p.exists():
                return p
    except Exception:
        pass
    # Fallback: relative to this file (dev mode)
    return Path(__file__).parent.parent / "templates"


def _copy_template(src: Path, dest: Path) -> None:
    if dest.exists():
        return
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dest)
    CREATED.append(str(dest))


def init(
    path: Annotated[Path, typer.Argument(help="Directory to initialise (default: current dir)")] = Path("."),
    force: Annotated[bool, typer.Option("--force", help="Overwrite existing files")] = False,
) -> None:
    """Scaffold a new SDA project — creates directory structure and starter files."""
    CREATED.clear()
    project = path.resolve()
    templates = _templates_dir()

    if not templates.exists():
        rprint("[red]Error:[/red] could not locate bundled templates directory")
        raise typer.Exit(1)

    # Create directory skeleton
    for d in SCAFFOLD_DIRS:
        (project / d).mkdir(parents=True, exist_ok=True)

    # Copy templates
    template_files = [
        ("architecture/adr/TEMPLATE.md", "architecture/adr/TEMPLATE.md"),
        ("architecture/inbox/PROB-TEMPLATE.yaml", "architecture/inbox/PROB-TEMPLATE.yaml"),
        ("architecture/model/services.yaml", "architecture/model/services.yaml"),
        ("OWNERS.yaml", "OWNERS.yaml"),
        ("workflows/aos-checks.yml", ".github/workflows/aos-checks.yml"),
    ]

    for src_rel, dest_rel in template_files:
        src = templates / src_rel
        dest = project / dest_rel
        if src.exists():
            if dest.exists() and not force:
                rprint(f"[dim]skip (exists):[/dim] {dest_rel}")
                continue
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dest)
            CREATED.append(dest_rel)

    # Generate empty index.yaml
    index_file = project / "architecture/index.yaml"
    if not index_file.exists() or force:
        index_file.write_text(
            "# AUTO-GENERATED by `sda index` — do not edit manually\ngraph: {}\n",
            encoding="utf-8",
        )
        CREATED.append("architecture/index.yaml")

    created_list = "\n".join(f"  [green]+[/green] {f}" for f in CREATED) or "  [dim](no new files)[/dim]"

    rprint(Panel(
        f"[bold]Project:[/bold] {project}\n\n"
        f"[bold]Created:[/bold]\n{created_list}\n\n"
        f"[dim]Next steps:[/dim]\n"
        f"  1. Fill in [bold]OWNERS.yaml[/bold] with your team details\n"
        f"  2. Run [bold]sda capture \"your first problem\"[/bold]\n"
        f"  3. Run [bold]sda check[/bold] to validate your setup",
        title="[bold green]ArchSpec Initialized[/bold green]",
        border_style="green",
    ))
