services:
  api-gateway:
    type: api
    depends_on:
      - auth
      - billing
    owner: architect@company.com
    last_reviewed: 2026-04-06
    labels: { area: payments, criticality: core }

  billing:
    type: api
    depends_on:
      - database
    owner: architect@company.com
    last_reviewed: 2026-04-06
    labels: { area: payments, criticality: core }

  database:
    type: postgres
    owner: architect@company.com
    last_reviewed: 2026-04-06
    labels: { area: platform, criticality: supporting, lifecycle: active }

  auth:
    type: api
    owner: architect@company.com
    last_reviewed: 2026-04-06
    labels: { area: platform, criticality: generic }
